require('dotenv').config();
const express=require('express'),multer=require('multer'),fs=require('fs'),path=require('path'),crypto=require('crypto'),{google}=require('googleapis');
const app=express(),PORT=process.env.PORT||3000,MAX=7;
const dir=path.join(__dirname,'uploads');if(!fs.existsSync(dir))fs.mkdirSync(dir,{recursive:true});
const upload=multer({dest:dir,limits:{fileSize:20*1024*1024*1024}});app.use(express.json());app.use(express.urlencoded({extended:true}));
const base=(process.env.RENDER_EXTERNAL_URL||`http://localhost:${PORT}`).replace(/\/$/,''),redirectUri=`${base}/oauth2callback`;
const data=path.join(__dirname,'data'),dbFile=path.join(data,'channels.json');if(!fs.existsSync(data))fs.mkdirSync(data,{recursive:true});
const read=()=>{try{return JSON.parse(fs.readFileSync(dbFile,'utf8'))}catch{return{channels:[]}}};const write=x=>fs.writeFileSync(dbFile,JSON.stringify(x,null,2));
const oauth=()=>new google.auth.OAuth2(process.env.GOOGLE_CLIENT_ID,process.env.GOOGLE_CLIENT_SECRET,redirectUri);
async function info(o){const y=google.youtube({version:'v3',auth:o}),r=await y.channels.list({part:['snippet','statistics'],mine:true}),c=r.data.items?.[0];if(!c)return null;return{channelId:c.id,title:c.snippet?.title||'YouTube Channel',thumbnail:c.snippet?.thumbnails?.high?.url||c.snippet?.thumbnails?.default?.url||'',subscribers:c.statistics?.subscriberCount||'0',videos:c.statistics?.videoCount||'0',views:c.statistics?.viewCount||'0'}}
app.get('/',(q,s)=>s.sendFile(path.join(__dirname,'index.html')));
app.get('/auth/:slot',(q,s)=>{let slot=+q.params.slot;if(!Number.isInteger(slot)||slot<1||slot>MAX)return s.status(400).send('Invalid slot');let state=Buffer.from(JSON.stringify({slot,nonce:crypto.randomBytes(16).toString('hex')})).toString('base64url');s.redirect(oauth().generateAuthUrl({access_type:'offline',prompt:'consent',scope:['https://www.googleapis.com/auth/youtube.upload'],state}))});
app.get('/oauth2callback',async(q,s)=>{try{if(!q.query.code||!q.query.state)return s.status(400).send('Authorization data missing');let st=JSON.parse(Buffer.from(q.query.state,'base64url').toString());let slot=+st.slot;if(slot<1||slot>MAX)return s.status(400).send('Invalid slot');let o=oauth(),{tokens}=await o.getToken(q.query.code);o.setCredentials(tokens);let i=await info(o);if(!i)return s.status(400).send('No YouTube channel found');let d=read(),old=d.channels.find(c=>c.slot===slot);d.channels=d.channels.filter(c=>c.slot!==slot);d.channels.push({slot,tokens:{...(old?.tokens||{}),...tokens},enabled:old?.enabled??true,...i});d.channels.sort((a,b)=>a.slot-b.slot);write(d);s.redirect('/?connected=1')}catch(e){console.error('OAuth callback error:',e.response?.data||e);s.status(500).send('YouTube authorization failed. Check Render logs.')}});
app.get('/api/channels',async(q,s)=>{let d=read(),out=[];for(let slot=1;slot<=MAX;slot++){let c=d.channels.find(x=>x.slot===slot);if(!c){out.push({slot,connected:false,title:`Channel ${slot}`,enabled:false});continue}try{let o=oauth();o.setCredentials(c.tokens);let i=await info(o);if(i)Object.assign(c,i);out.push({slot,connected:!!i,title:c.title,thumbnail:c.thumbnail,enabled:!!c.enabled,channelId:c.channelId})}catch{out.push({slot,connected:false,title:c.title,thumbnail:c.thumbnail,enabled:!!c.enabled,channelId:c.channelId})}}write(d);s.json({channels:out})});
app.post('/api/channels/:slot/toggle',(q,s)=>{let slot=+q.params.slot,d=read(),c=d.channels.find(x=>x.slot===slot);if(!c)return s.status(404).json({error:'Channel is not connected.'});c.enabled=!!q.body.enabled;write(d);s.json({success:true,enabled:c.enabled})});
app.post('/api/upload',upload.fields([{name:'video',maxCount:1},{name:'thumbnail',maxCount:1}]),async(q,s)=>{let v=q.files?.video?.[0],t=q.files?.thumbnail?.[0];try{if(!v)return s.status(400).json({error:'Video is required.'});let d=read(),targets=d.channels.filter(c=>c.tokens&&c.enabled);if(!targets.length)return s.status(400).json({error:'Enable at least one connected channel.'});let title=(q.body.title||'Untitled Video').trim(),description=q.body.description||'',privacy=['public','unlisted','private'].includes(q.body.privacy)?q.body.privacy:'private',tags=(q.body.tags||'').split(',').map(x=>x.trim()).filter(Boolean),results=[];for(const c of targets){try{let o=oauth();o.setCredentials(c.tokens);o.on('tokens',n=>{c.tokens={...(c.tokens||{}),...n};write(d)});let y=google.youtube({version:'v3',auth:o}),r=await y.videos.insert({part:['snippet','status'],requestBody:{snippet:{title,description,tags},status:{privacyStatus:privacy}},media:{mimeType:v.mimetype||'video/*',body:fs.createReadStream(v.path)},resumable:true}),id=r.data.id,th=false;if(t&&id)try{await y.thumbnails.set({videoId:id,media:{mimeType:t.mimetype,body:fs.createReadStream(t.path)}});th=true}catch(e){console.error('Thumbnail error:',e.response?.data||e)}results.push({slot:c.slot,title:c.title,success:true,thumbnailUploaded:th,videoId:id,url:`https://www.youtube.com/watch?v=${id}`})}catch(e){results.push({slot:c.slot,title:c.title,success:false,error:e.response?.data?.error?.message||e.message||'Upload failed'})}}s.json({success:results.some(x=>x.success),results})}catch(e){s.status(500).json({error:e.message||'Upload failed'})}finally{for(const f of[v,t])if(f?.path)try{fs.unlinkSync(f.path)}catch{}}});
app.get('/health',(q,s)=>s.json({status:'ok',service:'YT Admin 7 Channel',redirectUri}));app.listen(PORT,()=>console.log('YT Admin 7 Channel running; OAuth:',redirectUri));
