require('dotenv').config();
const express=require('express');
const multer=require('multer');
const fs=require('fs');
const path=require('path');
const crypto=require('crypto');
const {google}=require('googleapis');
const {Pool}=require('pg');

const app=express();
const PORT=process.env.PORT||3000;
const ADMIN_PASSWORD=process.env.ADMIN_PASSWORD||'';
const SESSION_SECRET=process.env.SESSION_SECRET||ADMIN_PASSWORD;
const SESSION_TTL=7*24*60*60*1000;
const SCOPES=['https://www.googleapis.com/auth/youtube.upload','https://www.googleapis.com/auth/youtube.readonly','https://www.googleapis.com/auth/youtube'];
const BASE_URL=(process.env.RENDER_EXTERNAL_URL||`http://localhost:${PORT}`).replace(/\/$/,'');
const YT_REDIRECT=`${BASE_URL}/oauth2callback`;
const META_REDIRECT=`${BASE_URL}/meta/oauth/callback`;
const META_GRAPH_VERSION=process.env.META_GRAPH_VERSION||'v25.0';
const META_APP_ID=process.env.META_APP_ID||'';
const META_APP_SECRET=process.env.META_APP_SECRET||'';
const META_CONFIG_ID=process.env.META_CONFIG_ID||'';
const META_SCOPES=(process.env.META_SCOPES||'pages_show_list,pages_read_engagement,pages_manage_posts,publish_video,instagram_basic,instagram_content_publish,instagram_manage_comments,business_management').split(',').map(x=>x.trim()).filter(Boolean);

const uploadDir=path.join(__dirname,'uploads'); if(!fs.existsSync(uploadDir))fs.mkdirSync(uploadDir,{recursive:true});
const upload=multer({dest:uploadDir,limits:{fileSize:20*1024*1024*1024}});
app.use(express.json({limit:'4mb'}));app.use(express.urlencoded({extended:true}));

// Durable state: use PostgreSQL in production. Local JSON is only a development fallback.
const pool=process.env.DATABASE_URL?new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.DATABASE_URL.includes('localhost')?false:{rejectUnauthorized:false}}):null;
const localDir=path.join(__dirname,'data');if(!fs.existsSync(localDir))fs.mkdirSync(localDir,{recursive:true});
const localFile=path.join(localDir,'state.json');
const DEFAULT_STATE={channels:[],facebook:[],instagram:[],collaborations:[],settings:{}};
function localRead(){try{return {...DEFAULT_STATE,...JSON.parse(fs.readFileSync(localFile,'utf8'))}}catch{return JSON.parse(JSON.stringify(DEFAULT_STATE))}}
function localWrite(s){fs.writeFileSync(localFile,JSON.stringify(s,null,2))}
async function initDb(){if(!pool)return;await pool.query(`CREATE TABLE IF NOT EXISTS app_state (id integer primary key, data jsonb not null, updated_at timestamptz not null default now())`);const r=await pool.query('SELECT id FROM app_state WHERE id=1');if(!r.rowCount){let state=localRead();await pool.query('INSERT INTO app_state(id,data) VALUES(1,$1)',[state]);}}
async function readState(){if(!pool)return localRead();const r=await pool.query('SELECT data FROM app_state WHERE id=1');return r.rows[0]?.data||JSON.parse(JSON.stringify(DEFAULT_STATE))}
async function writeState(s){if(!pool)return localWrite(s);await pool.query('INSERT INTO app_state(id,data,updated_at) VALUES(1,$1,now()) ON CONFLICT(id) DO UPDATE SET data=EXCLUDED.data,updated_at=now()',[s])}

function sign(payload){const body=JSON.stringify(payload);const sig=crypto.createHmac('sha256',SESSION_SECRET).update(body).digest('hex');return Buffer.from(JSON.stringify({p:payload,sig})).toString('base64url')}
function verify(raw){const x=JSON.parse(Buffer.from(String(raw),'base64url').toString('utf8'));const body=JSON.stringify(x.p);const sig=crypto.createHmac('sha256',SESSION_SECRET).update(body).digest('hex');if(x.sig!==sig||Number(x.p.exp)<Date.now())throw new Error('Invalid or expired state');return x.p}
function sessionToken(exp){const raw=String(exp);return `${raw}.${crypto.createHmac('sha256',SESSION_SECRET).update(raw).digest('hex')}`}
function validSession(token){try{if(!token||!SESSION_SECRET)return false;const [exp,sig]=String(token).split('.');const expected=crypto.createHmac('sha256',SESSION_SECRET).update(exp).digest('hex');return Number(exp)>=Date.now()&&crypto.timingSafeEqual(Buffer.from(sig),Buffer.from(expected))}catch{return false}}
function cookie(req){return (req.headers.cookie||'').split(';').map(x=>x.trim()).find(x=>x.startsWith('admin_session='))?.split('=')[1]||''}
function isAdmin(req){return validSession(cookie(req))||validSession(req.headers['x-admin-session'])}
function requireAdmin(req,res,next){if(!isAdmin(req))return res.status(401).json({error:'Admin login required.'});next()}
function oauth(){return new google.auth.OAuth2(process.env.GOOGLE_CLIENT_ID,process.env.GOOGLE_CLIENT_SECRET,YT_REDIRECT)}
function metaUrl(p,params={}){const u=new URL(`https://graph.facebook.com/${META_GRAPH_VERSION}${p}`);for(const[k,v]of Object.entries(params))if(v!==undefined)u.searchParams.set(k,String(v));return u}
async function metaJson(p,params={},opts={}){const u=metaUrl(p,params);const r=await fetch(u,{method:opts.method||'GET',headers:opts.headers||{},body:opts.body});const text=await r.text();let d={};try{d=JSON.parse(text)}catch{}if(!r.ok||d.error)throw new Error(d?.error?.message||`Meta API HTTP ${r.status}`);return d}
function parse(v){if(!v)return null;const d=new Date(v);return Number.isNaN(d.getTime())?null:d.toISOString()}
function mediaToken(p){return sign({p,e:Date.now()+20*60*1000,n:crypto.randomBytes(10).toString('hex')})}

app.get('/',(req,res)=>res.sendFile(path.join(__dirname,'index.html')));
app.get('/health',async(req,res)=>res.json({status:'ok',database:!!pool,persistence:pool?'postgresql':'local-only',redirectUri:YT_REDIRECT,metaRedirectUri:META_REDIRECT}));
app.post('/api/login',(req,res)=>{if(!ADMIN_PASSWORD)return res.status(500).json({error:'ADMIN_PASSWORD is not configured.'});const a=Buffer.from(String(req.body.password||'')),b=Buffer.from(ADMIN_PASSWORD);if(a.length!==b.length||!crypto.timingSafeEqual(a,b))return res.status(401).json({error:'Incorrect password.'});res.setHeader('Set-Cookie',`admin_session=${sessionToken(Date.now()+SESSION_TTL)}; HttpOnly; Secure; SameSite=Lax; Path=/; Max-Age=${SESSION_TTL/1000}`);res.json({success:true})});
app.post('/api/logout',(req,res)=>{res.setHeader('Set-Cookie','admin_session=; HttpOnly; Secure; SameSite=Lax; Path=/; Max-Age=0');res.json({success:true})});
app.get('/api/auth-status',(req,res)=>res.json({loggedIn:isAdmin(req),persistent:!!pool}));

async function ytChannelInfo(auth){const y=google.youtube({version:'v3',auth});const r=await y.channels.list({part:['snippet','statistics','contentDetails'],mine:true});const c=r.data.items?.[0];if(!c)return null;return{channelId:c.id,title:c.snippet?.title||'YouTube Channel',thumbnail:c.snippet?.thumbnails?.high?.url||c.snippet?.thumbnails?.default?.url||'',subscribers:c.statistics?.subscriberCount||'0',videos:c.statistics?.videoCount||'0',views:c.statistics?.viewCount||'0',uploadsPlaylistId:c.contentDetails?.relatedPlaylists?.uploads||''}}

app.get('/auth/new',requireAdmin,(req,res)=>{const id=crypto.randomUUID();const state=sign({accountId:id,exp:Date.now()+10*60*1000,nonce:crypto.randomBytes(12).toString('hex')});res.redirect(oauth().generateAuthUrl({access_type:'offline',prompt:'consent',include_granted_scopes:true,scope:SCOPES,state}))});
app.get('/oauth2callback',async(req,res)=>{try{if(req.query.error)return res.redirect('/?yt=cancelled');const s=verify(req.query.state);const o=oauth();const{tokens}=await o.getToken(req.query.code);o.setCredentials(tokens);const info=await ytChannelInfo(o);if(!info)throw new Error('No YouTube channel found.');const db=await readState();db.channels=db.channels||[];const old=db.channels.find(x=>x.id===s.accountId);db.channels=db.channels.filter(x=>x.id!==s.accountId);db.channels.push({id:s.accountId,enabled:old?.enabled??true,createdAt:old?.createdAt||new Date().toISOString(),tokens:{...(old?.tokens||{}),...tokens},...info});await writeState(db);res.redirect('/?yt=connected')}catch(e){console.error(e.response?.data||e);res.status(500).send('YouTube authorization failed. Check Render logs.')}});
app.get('/api/channels',requireAdmin,async(req,res)=>{const db=await readState();const out=[];for(const c of db.channels||[]){try{const o=oauth();o.setCredentials(c.tokens);const fresh=await ytChannelInfo(o);if(fresh)Object.assign(c,fresh);out.push({...c,tokens:undefined,connected:true})}catch{out.push({...c,tokens:undefined,connected:true,reauthorize:true})}}await writeState(db);res.json({channels:out,persistent:!!pool})});
app.post('/api/channels/:id/toggle',requireAdmin,async(req,res)=>{const db=await readState();const c=(db.channels||[]).find(x=>x.id===req.params.id);if(!c)return res.status(404).json({error:'Channel not found'});c.enabled=!!req.body.enabled;await writeState(db);res.json({success:true,enabled:c.enabled})});
app.delete('/api/channels/:id',requireAdmin,async(req,res)=>{const db=await readState();db.channels=(db.channels||[]).filter(x=>x.id!==req.params.id);await writeState(db);res.json({success:true})});

app.get('/api/playlists/:id',requireAdmin,async(req,res)=>{try{const db=await readState(),c=(db.channels||[]).find(x=>x.id===req.params.id);if(!c)return res.status(404).json({error:'Channel not found'});const o=oauth();o.setCredentials(c.tokens);const y=google.youtube({version:'v3',auth:o});let items=[],pageToken='';do{const r=await y.playlists.list({part:['snippet','status'],mine:true,maxResults:50,pageToken:pageToken||undefined});items.push(...r.data.items||[]);pageToken=r.data.nextPageToken||''}while(pageToken&&items.length<500);res.json({playlists:items.map(p=>({id:p.id,title:p.snippet?.title||'',privacy:p.status?.privacyStatus||''}))})}catch(e){res.status(500).json({error:e.response?.data?.error?.message||e.message})}});

// Meta OAuth + account discovery. Each Page and linked Professional Instagram account becomes its own durable target.
app.get('/meta/connect',requireAdmin,(req,res)=>{if(!META_APP_ID||!META_APP_SECRET)return res.status(500).send('Meta App ID/Secret missing on Render.');const state=sign({exp:Date.now()+10*60*1000,nonce:crypto.randomBytes(12).toString('hex')});const u=new URL(`https://www.facebook.com/${META_GRAPH_VERSION}/dialog/oauth`);u.searchParams.set('client_id',META_APP_ID);u.searchParams.set('redirect_uri',META_REDIRECT);u.searchParams.set('state',state);u.searchParams.set('response_type','code');if(META_CONFIG_ID)u.searchParams.set('config_id',META_CONFIG_ID);else u.searchParams.set('scope',META_SCOPES.join(','));res.redirect(u.toString())});
app.get('/meta/oauth/callback',async(req,res)=>{try{verify(req.query.state);const tr=await fetch(metaUrl('/oauth/access_token',{client_id:META_APP_ID,client_secret:META_APP_SECRET,redirect_uri:META_REDIRECT,code:req.query.code}));const td=await tr.json();if(!tr.ok||td.error)throw new Error(td?.error?.message||'Meta token exchange failed');const pages=await metaJson('/me/accounts',{access_token:td.access_token,fields:'id,name,access_token,picture,instagram_business_account{id,username,name,profile_picture_url}'});const db=await readState();db.facebook=db.facebook||[];db.instagram=db.instagram||[];for(const p of pages.data||[]){const old=db.facebook.find(x=>x.id===p.id);db.facebook=db.facebook.filter(x=>x.id!==p.id);db.facebook.push({id:p.id,name:p.name||'Facebook Page',picture:p.picture?.data?.url||'',accessToken:p.access_token,enabled:old?.enabled??true,connectedAt:old?.connectedAt||new Date().toISOString()});const ig=p.instagram_business_account;if(ig?.id){const oi=db.instagram.find(x=>x.id===ig.id);db.instagram=db.instagram.filter(x=>x.id!==ig.id);db.instagram.push({id:ig.id,username:ig.username||ig.name||'Instagram',name:ig.name||ig.username||'Instagram',picture:ig.profile_picture_url||'',pageId:p.id,pageName:p.name||'',accessToken:p.access_token,enabled:oi?.enabled??true,connectedAt:oi?.connectedAt||new Date().toISOString()})}}await writeState(db);res.redirect('/?meta=connected')}catch(e){console.error('Meta OAuth',e.response?.data||e);res.status(500).send('Meta authorization failed. Check permissions, configuration ID and Render logs.')}});
app.get('/api/social',requireAdmin,async(req,res)=>{const db=await readState();res.json({facebook:(db.facebook||[]).map(x=>({...x,accessToken:undefined})),instagram:(db.instagram||[]).map(x=>({...x,accessToken:undefined})),persistent:!!pool})});
app.post('/api/social/:type/:id/toggle',requireAdmin,async(req,res)=>{const db=await readState();const arr=req.params.type==='facebook'?db.facebook:req.params.type==='instagram'?db.instagram:null;if(!arr)return res.status(400).json({error:'Invalid platform'});const x=arr.find(a=>a.id===req.params.id);if(!x)return res.status(404).json({error:'Account not found'});x.enabled=!!req.body.enabled;await writeState(db);res.json({success:true})});
app.delete('/api/social/:type/:id',requireAdmin,async(req,res)=>{const db=await readState();if(req.params.type==='facebook')db.facebook=(db.facebook||[]).filter(x=>x.id!==req.params.id);if(req.params.type==='instagram')db.instagram=(db.instagram||[]).filter(x=>x.id!==req.params.id);await writeState(db);res.json({success:true})});

// Collaboration presets. Actual Instagram publishing can pass collaborators when the selected account(s) are Professional accounts.
app.get('/api/collaborations',requireAdmin,async(req,res)=>{const db=await readState();res.json({collaborations:db.collaborations||[]})});
app.post('/api/collaborations',requireAdmin,async(req,res)=>{const db=await readState();const members=Array.isArray(req.body.members)?req.body.members:[];const name=String(req.body.name||'Collaboration').trim();const id=req.body.id||crypto.randomUUID();db.collaborations=(db.collaborations||[]).filter(x=>x.id!==id);db.collaborations.push({id,name,members,createdAt:new Date().toISOString()});await writeState(db);res.json({success:true})});
app.delete('/api/collaborations/:id',requireAdmin,async(req,res)=>{const db=await readState();db.collaborations=(db.collaborations||[]).filter(x=>x.id!==req.params.id);await writeState(db);res.json({success:true})});

app.get('/media/:token',async(req,res)=>{try{const p=verify(req.params.token);if(!p.p||p.e<Date.now()||!fs.existsSync(p.p))return res.status(404).send('Media unavailable');res.sendFile(path.resolve(p.p))}catch{return res.status(403).send('Invalid media URL')}});

app.post('/api/upload',requireAdmin,upload.fields([{name:'video',maxCount:1},{name:'thumbnail',maxCount:1},{name:'image',maxCount:1}]),async(req,res)=>{
 const video=req.files?.video?.[0],thumb=req.files?.thumbnail?.[0],image=req.files?.image?.[0];
 try{
  const db=await readState();const yt=(db.channels||[]).filter(x=>x.enabled&&x.tokens);const fb=(db.facebook||[]).filter(x=>x.enabled&&JSON.parse(req.body.facebookTargets||'[]').includes(x.id));const ig=(db.instagram||[]).filter(x=>x.enabled&&JSON.parse(req.body.instagramTargets||'[]').includes(x.id));
  const type=req.body.contentType||'video';
  if(!yt.length&&!fb.length&&!ig.length)return res.status(400).json({error:'Enable/select at least one publishing account.'});
  const title=String(req.body.title||'Untitled').trim(),description=String(req.body.description||'');const tags=description?String(req.body.tags||'').split(',').map(x=>x.trim()).filter(Boolean):[];
  const results=[];
  if(type==='community'){
   // YouTube channel bulletins/community posts are not generally exposed as a current public create endpoint; keep this explicit.
   for(const c of yt)results.push({platform:'youtube',title:c.title,success:false,error:'YouTube Community post creation is not exposed by the public Data API. Open YouTube Studio for this action.'});
  } else if(type==='story'){
   // Instagram Stories are available through the API only for eligible Professional business accounts; Facebook Page story APIs are restricted/version-dependent.
   for(const x of ig){try{const tok=mediaToken((image||video)?.path);const url=`${BASE_URL}/media/${encodeURIComponent(tok)}`;const params={access_token:x.accessToken,media_type:'STORIES'};if(image)params.image_url=url;else params.video_url=url;const c=await metaJson(`/${x.id}/media`,{}, {method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams(params)});const p=await metaJson(`/${x.id}/media_publish`,{}, {method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({access_token:x.accessToken,creation_id:c.id})});results.push({platform:'instagram',title:x.username,success:true,id:p.id})}catch(e){results.push({platform:'instagram',title:x.username,success:false,error:e.message})}}
   for(const x of fb)results.push({platform:'facebook',title:x.name,success:false,error:'Facebook Story publishing is not exposed here because availability depends on the current Page API permissions/version. Use the Facebook Page publishing surface.'});
  } else if(type==='post'){
   if(image||video){for(const x of fb){try{let d;if(image){const f=new FormData();f.append('access_token',x.accessToken);f.append('message',req.body.facebookCaption||description);f.append('source',new Blob([fs.readFileSync(image.path)],{type:image.mimetype||'image/jpeg'}),image.originalname||'image');const r=await fetch(metaUrl(`/${x.id}/photos`),{method:'POST',body:f});d=await r.json();if(!r.ok||d.error)throw new Error(d?.error?.message||'Facebook post failed')}else{const f=new FormData();f.append('access_token',x.accessToken);f.append('description',req.body.facebookCaption||description);f.append('source',new Blob([fs.readFileSync(video.path)],{type:video.mimetype||'video/mp4'}),video.originalname||'video');const r=await fetch(metaUrl(`/${x.id}/videos`),{method:'POST',body:f});d=await r.json();if(!r.ok||d.error)throw new Error(d?.error?.message||'Facebook video failed')}results.push({platform:'facebook',title:x.name,success:true,id:d.id,url:`https://www.facebook.com/${d.id}`})}catch(e){results.push({platform:'facebook',title:x.name,success:false,error:e.message})}}
    for(const x of ig){try{const media=image||video;if(!media)throw new Error('Image or video required');const tok=mediaToken(media.path),url=`${BASE_URL}/media/${encodeURIComponent(tok)}`;const p={access_token:x.accessToken,caption:req.body.instagramCaption||description};if(image){p.image_url=url}else{p.media_type='REELS';p.video_url=url;p.share_to_feed='true'};if(req.body.collaborators)p.collaborators=req.body.collaborators;const c=await metaJson(`/${x.id}/media`,{}, {method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams(p)});for(let i=0;i<30;i++){await new Promise(r=>setTimeout(r,2000));const s=await metaJson(`/${c.id}`,{access_token:x.accessToken,fields:'status_code,status'});if(s.status_code==='ERROR')throw new Error(s.status||'Instagram processing error');if(s.status_code==='FINISHED')break}const p2=await metaJson(`/${x.id}/media_publish`,{}, {method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({access_token:x.accessToken,creation_id:c.id})});results.push({platform:'instagram',title:x.username,success:true,id:p2.id})}catch(e){results.push({platform:'instagram',title:x.username,success:false,error:e.message})}}
   }
  } else {
   if(!video)return res.status(400).json({error:'Video is required.'});
   const schedule=parse(req.body.publishAt);const publishMode=req.body.publishMode||'private';const privacy=publishMode==='schedule'?'private':(['public','unlisted','private'].includes(publishMode)?publishMode:'private');
   for(const c of yt){try{const o=oauth();o.setCredentials(c.tokens);o.on('tokens',async t=>{c.tokens={...(c.tokens||{}),...t};try{await writeState(db)}catch{}});const y=google.youtube({version:'v3',auth:o});const status={privacyStatus:privacy,license:req.body.license||'youtube',embeddable:req.body.embeddable!=='false',publicStatsViewable:req.body.publicStats!=='false',selfDeclaredMadeForKids:req.body.madeForKids==='true',containsSyntheticMedia:req.body.syntheticMedia==='true'};if(schedule)status.publishAt=schedule;const body={snippet:{title,description,tags,categoryId:String(req.body.categoryId||'22')},status};if(req.body.language)body.snippet.defaultLanguage=req.body.language;if(req.body.recordingDate)body.recordingDetails={recordingDate:parse(req.body.recordingDate)};const r=await y.videos.insert({part:['snippet','status','recordingDetails'],notifySubscribers:req.body.notifySubscribers!=='false',requestBody:body,media:{mimeType:video.mimetype||'video/mp4',body:fs.createReadStream(video.path)},resumable:true});let thumbOK=false;if(thumb){try{await y.thumbnails.set({videoId:r.data.id,media:{mimeType:thumb.mimetype,body:fs.createReadStream(thumb.path)}});thumbOK=true}catch{}}results.push({platform:'youtube',title:c.title,success:true,id:r.data.id,thumbnailUploaded:thumbOK,url:`https://www.youtube.com/watch?v=${r.data.id}`})}catch(e){results.push({platform:'youtube',title:c.title,success:false,error:e.response?.data?.error?.message||e.message})}}
   for(const x of fb){try{const f=new FormData();f.append('access_token',x.accessToken);f.append('description',req.body.facebookCaption||description);f.append('published','true');f.append('source',new Blob([fs.readFileSync(video.path)],{type:video.mimetype||'video/mp4'}),video.originalname||'video');const r=await fetch(metaUrl(`/${x.id}/videos`),{method:'POST',body:f});const d=await r.json();if(!r.ok||d.error)throw new Error(d?.error?.message||'Facebook upload failed');results.push({platform:'facebook',title:x.name,success:true,id:d.id,url:`https://www.facebook.com/${d.id}`})}catch(e){results.push({platform:'facebook',title:x.name,success:false,error:e.message})}}
   for(const x of ig){try{const tok=mediaToken(video.path),url=`${BASE_URL}/media/${encodeURIComponent(tok)}`;const p={access_token:x.accessToken,media_type:'REELS',video_url:url,caption:req.body.instagramCaption||description,share_to_feed:'true'};if(req.body.collaborators)p.collaborators=req.body.collaborators;const c=await metaJson(`/${x.id}/media`,{}, {method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams(p)});let finished=false;for(let i=0;i<30;i++){await new Promise(r=>setTimeout(r,2000));const s=await metaJson(`/${c.id}`,{access_token:x.accessToken,fields:'status_code,status'});if(s.status_code==='ERROR'||s.status_code==='EXPIRED')throw new Error(s.status||'Instagram processing failed');if(s.status_code==='FINISHED'){finished=true;break}}if(!finished)throw new Error('Instagram processing timed out.');const p2=await metaJson(`/${x.id}/media_publish`,{}, {method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({access_token:x.accessToken,creation_id:c.id})});results.push({platform:'instagram',title:x.username,success:true,id:p2.id})}catch(e){results.push({platform:'instagram',title:x.username,success:false,error:e.message})}}
  }
  res.json({success:results.some(x=>x.success),results,persistent:!!pool});
 }catch(e){console.error('upload',e);res.status(500).json({error:e.message||'Upload failed'})}
 finally{for(const f of [video,thumb,image])if(f?.path)try{fs.unlinkSync(f.path)}catch{}}
});

initDb().then(()=>app.listen(PORT,()=>console.log(`YT Admin Studio v4 running on ${PORT} | persistence=${!!pool}`))).catch(e=>{console.error('DB init failed',e);process.exit(1)});
