require("dotenv").config();
const express=require("express"),multer=require("multer"),fs=require("fs"),path=require("path"),{google}=require("googleapis");
const app=express(),PORT=process.env.PORT||3000;
const uploadDir=path.join(__dirname,"uploads"); if(!fs.existsSync(uploadDir))fs.mkdirSync(uploadDir,{recursive:true});
const upload=multer({dest:uploadDir,limits:{fileSize:20*1024*1024*1024}});
app.use(express.json()); app.use(express.urlencoded({extended:true}));
const baseUrl=(process.env.RENDER_EXTERNAL_URL||`http://localhost:${PORT}`).replace(/\/$/,"");
const redirectUri=`${baseUrl}/oauth2callback`;
const oauth2Client=new google.auth.OAuth2(process.env.GOOGLE_CLIENT_ID,process.env.GOOGLE_CLIENT_SECRET,redirectUri);
const tokenFile=path.join(__dirname,"tokens.json");
function saveTokens(t){fs.writeFileSync(tokenFile,JSON.stringify(t,null,2));}
function loadTokens(){if(!fs.existsSync(tokenFile))return null;try{return JSON.parse(fs.readFileSync(tokenFile,"utf8"));}catch{return null;}}
const saved=loadTokens(); if(saved)oauth2Client.setCredentials(saved);
oauth2Client.on("tokens",tokens=>{const old=loadTokens()||{};saveTokens({...old,...tokens});});
app.get("/",(req,res)=>res.sendFile(path.join(__dirname,"index.html")));
app.get("/auth",(req,res)=>{const p=new URLSearchParams({client_id:process.env.GOOGLE_CLIENT_ID||"",redirect_uri:redirectUri,response_type:"code",scope:"https://www.googleapis.com/auth/youtube.upload",access_type:"offline",prompt:"consent"});res.redirect(`https://accounts.google.com/o/oauth2/v2/auth?${p.toString()}`);});
app.get("/oauth2callback",async(req,res)=>{try{if(!req.query.code)return res.status(400).send("Authorization code missing.");const {tokens}=await oauth2Client.getToken(req.query.code);oauth2Client.setCredentials(tokens);saveTokens(tokens);res.redirect("/?connected=1");}catch(e){console.error("OAuth callback error:",e.response?.data||e);res.status(500).send("YouTube authorization failed. Check Render logs.");}});
app.get("/api/status",async(req,res)=>{try{const tokens=loadTokens();if(!tokens)return res.json({connected:false});oauth2Client.setCredentials(tokens);const yt=google.youtube({version:"v3",auth:oauth2Client});const r=await yt.channels.list({part:["snippet","statistics"],mine:true});const c=r.data.items?.[0];if(!c)return res.json({connected:false});res.json({connected:true,channel:{id:c.id,title:c.snippet?.title||"YouTube Channel",thumbnail:c.snippet?.thumbnails?.high?.url||c.snippet?.thumbnails?.default?.url||"",subscribers:c.statistics?.subscriberCount||"0",videos:c.statistics?.videoCount||"0",views:c.statistics?.viewCount||"0"}});}catch(e){console.error("Status error:",e.response?.data||e.message||e);res.json({connected:false});}});
app.post("/api/upload",upload.fields([{name:"video",maxCount:1},{name:"thumbnail",maxCount:1}]),async(req,res)=>{const v=req.files?.video?.[0],t=req.files?.thumbnail?.[0];try{const tokens=loadTokens();if(!tokens)return res.status(401).json({error:"Connect YouTube first."});if(!v)return res.status(400).json({error:"Video is required."});oauth2Client.setCredentials(tokens);const yt=google.youtube({version:"v3",auth:oauth2Client});const title=(req.body.title||"Untitled Video").trim(),description=req.body.description||"",privacy=["public","unlisted","private"].includes(req.body.privacy)?req.body.privacy:"private",tags=(req.body.tags||"").split(",").map(x=>x.trim()).filter(Boolean);console.log("Starting YouTube upload:",title);const r=await yt.videos.insert({part:["snippet","status"],requestBody:{snippet:{title,description,tags},status:{privacyStatus:privacy}},media:{mimeType:v.mimetype||"video/*",body:fs.createReadStream(v.path)},resumable:true});const videoId=r.data.id;let thumbnailUploaded=false;if(t&&videoId){try{await yt.thumbnails.set({videoId,media:{mimeType:t.mimetype,body:fs.createReadStream(t.path)}});thumbnailUploaded=true;}catch(e){console.error("Thumbnail error:",e.response?.data||e);}}res.json({success:true,videoId,thumbnailUploaded,url:`https://www.youtube.com/watch?v=${videoId}`});}catch(e){console.error("Upload error:",e.response?.data||e);res.status(500).json({error:e.response?.data?.error?.message||e.message||"YouTube upload failed."});}finally{for(const f of [v,t])if(f?.path)try{fs.unlinkSync(f.path)}catch{}}});
app.get("/health",(req,res)=>res.json({status:"ok",service:"YT Admin",redirectUri}));
app.listen(PORT,()=>console.log("YT Admin Pro running | Port:",PORT,"| OAuth Redirect URI:",redirectUri));
